const QUANTOM_BASE_PATH="Quantom";
export const GET_QUANTOM_REPORT_URL=`${QUANTOM_BASE_PATH}/GetReport`;
export const GET_ALL_QUANTOM_REPORTS_URL=`${QUANTOM_BASE_PATH}/GetAllReports`
export const GET_ALL_QUANTOM_REPORT_SCHEMA_CONTEXT_URL=`${QUANTOM_BASE_PATH}/GetReportSchemaContext`
export const FILL_REPORT_FILTER_BY_REPORT_NAME=`${QUANTOM_BASE_PATH}/FillReportFilter`